Remove Solaris cruft

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,7 +9,6 @@
 PKG_CONFIG_NAME="harfbuzz freetype2 fribidi"
 PKG_DEB_NAME="libharfbuzz-dev libfribidi-dev"
 PKG_RPM_NAME="harfbuzz-devel fribidi-devel"
-PKG_CSW_NAME="libharfbuzz_dev libfribidi_dev"
 PKG_BREW_NAME="harfbuzz fribidi"
 PKG_TEST_HEADER="#include <hb-ft.h>"
 PKG_LIBS="-lfreetype -lharfbuzz -lfribidi -lpng"
@@ -60,25 +59,19 @@ echo "$PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/d
 
 # Customize the error
 if [ $? -ne 0 ]; then
-  if [ "`uname`" = "SunOS" ]; then
-    PKG_CFLAGS="$PKG_CFLAGS -DNO_HARFBUZZ_FRIBIDI"
-    PKG_LIBS=""
-  else
-    echo "--------------------------- [ANTICONF] --------------------------------"
-    echo "Configuration failed to find the $PKG_CONFIG_NAME library. Try installing:"
-    echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
-    echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
-    echo " * csw: $PKG_CSW_NAME (Solaris)"
-    echo " * brew: $PKG_BREW_NAME (OSX)"
-    echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
-    echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
-    echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
-    echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-    echo "-------------------------- [ERROR MESSAGE] ---------------------------"
-    cat configure.log
-    echo "--------------------------------------------------------------------"
-    exit 1
-  fi
+  echo "--------------------------- [ANTICONF] --------------------------------"
+  echo "Configuration failed to find the $PKG_CONFIG_NAME library. Try installing:"
+  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+  echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
+  echo " * brew: $PKG_BREW_NAME (OSX)"
+  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
+  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
+  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+  echo "-------------------------- [ERROR MESSAGE] ---------------------------"
+  cat configure.log
+  echo "--------------------------------------------------------------------"
+  exit 1
 fi
 
 # Write to Makevars
